jwt:
  secret: ${SECRET_KEY:secret}
server:
  port: ${SERVER_PORT:9007}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/books_dbnew4}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Mysql@123}
  jpa:
    hibernate:
      ddl-auto: update
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true    

